# Generated by Django 5.1.1 on 2024-10-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('famille', models.CharField(choices=[('MI', 'MI'), ('MB', 'MB'), ('MM', 'MM'), ('EM', 'EM')], max_length=50)),
                ('origine', models.CharField(max_length=50)),
                ('quantite', models.IntegerField()),
                ('emplacement', models.CharField(blank=True, max_length=255)),
                ('etat', models.CharField(default='Bon', max_length=50)),
                ('code_article', models.CharField(blank=True, max_length=50, unique=True)),
            ],
        ),
    ]
