# Generated by Django 5.1.1 on 2024-09-30 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='location',
            new_name='emplacement',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='status',
            new_name='etat',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='family',
            new_name='famille',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='origin',
            new_name='origine',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='quantity',
            new_name='quantité',
        ),
    ]
