# Generated by Django 5.1.1 on 2024-09-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_app', '0003_rename_quantité_article_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='famille',
            field=models.CharField(choices=[('MI', 'MI'), ('MB', 'MB'), ('MM', 'MM'), ('EM', 'EM')], max_length=50),
        ),
    ]
