# Generated by Django 5.1.1 on 2024-09-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_app', '0004_alter_article_famille'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='code_article',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
